### ISSUE TITLE
Unique identifier for "Unreleased" spirits

### ISSUE THREAD

**Issue by TheOriginalSoni** [nathanj/spirit-island-pbp#60]
Right now it's not clear from a quick glance what spirits are "unofficially official" in any capacity.

All Rots, Exploratory Bringer, Covets are all at some level of "By SI authors but not official-official". We should add a tag to their namees to make it clearer.

**Comment by TheOriginalSoni** [comment]
I suggest "Unreleased"

So it will be like `Bringer - Exploratory (Unreleased)` or `Covets (Unreleased)`

**Comment by petertseng** [comment]
I see what you mean by Unreleased, though I think I'd want to look for another term like Non-Canon or Unpublished. Both Apocrypha spirits had multiple formal releases with version numbers and everything, which is why Unreleased doesn't seem right.

Another option is just to call them what they are. Spreading Rot and Covets Gleaming Shards of Earth are Apocrypha spirits and should get labeled as such, and Exploratory Bringer is an exploratory testing spirit and it should get labeled as such

**Comment by petertseng** [comment]
I tentatively marked my PR as closing this. Give a shout if it seems insufficient. I think it would be fine to add a parenthetical after the Apocrypha and Exploratory Testing categories if that's needed.
